// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Sms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.didadu.generate.sms;

public interface ISmsService extends Ice.Object,
                                     _ISmsServiceOperations, _ISmsServiceOperationsNC
{
    public static final String ice_staticId = "::sms::ISmsService";

    public static final long serialVersionUID = 4525168598162248201L;
}
