// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Goodbye.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.didadu.generate.goodbye;

public interface Bye extends Ice.Object,
                             _ByeOperations, _ByeOperationsNC
{
    public static final String ice_staticId = "::goodbye::Bye";

    public static final long serialVersionUID = -1979587788293372322L;
}
