// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo2;

public interface ClockPrx extends Ice.ObjectPrx
{
    public TimeOfDay getTime();

    public TimeOfDay getTime(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTime();

    public Ice.AsyncResult begin_getTime(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getTime(Ice.Callback __cb);

    public Ice.AsyncResult begin_getTime(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getTime(Callback_Clock_getTime __cb);

    public Ice.AsyncResult begin_getTime(java.util.Map<String, String> __ctx, Callback_Clock_getTime __cb);

    public Ice.AsyncResult begin_getTime(IceInternal.Functional_GenericCallback1<TimeOfDay> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getTime(IceInternal.Functional_GenericCallback1<TimeOfDay> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getTime(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<TimeOfDay> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getTime(java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<TimeOfDay> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public TimeOfDay end_getTime(Ice.AsyncResult __result);

    public void setTime(TimeOfDay time);

    public void setTime(TimeOfDay time, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setTime(TimeOfDay time);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, Ice.Callback __cb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, Callback_Clock_setTime __cb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, java.util.Map<String, String> __ctx, Callback_Clock_setTime __cb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_setTime(TimeOfDay time, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_setTime(Ice.AsyncResult __result);
}
