// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `interface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo2;

public interface Clock extends Ice.Object,
                               _ClockOperations, _ClockOperationsNC
{
    public static final String ice_staticId = "::demo2::Clock";

    public static final long serialVersionUID = 9165314421464188484L;
}
