// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public class Point implements java.lang.Cloneable, java.io.Serializable
{
    public short x;

    public short y;

    public Point()
    {
    }

    public Point(short x, short y)
    {
        this.x = x;
        this.y = y;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Point _r = null;
        if(rhs instanceof Point)
        {
            _r = (Point)rhs;
        }

        if(_r != null)
        {
            if(x != _r.x)
            {
                return false;
            }
            if(y != _r.y)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::demo::Point");
        __h = IceInternal.HashUtil.hashAdd(__h, x);
        __h = IceInternal.HashUtil.hashAdd(__h, y);
        return __h;
    }

    public Point
    clone()
    {
        Point c = null;
        try
        {
            c = (Point)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeShort(x);
        __os.writeShort(y);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        x = __is.readShort();
        y = __is.readShort();
    }

    static public void
    __write(IceInternal.BasicStream __os, Point __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public Point
    __read(IceInternal.BasicStream __is, Point __v)
    {
        if(__v == null)
        {
             __v = new Point();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final Point __nullMarshalValue = new Point();

    public static final long serialVersionUID = -7724337955338316155L;
}
