// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public final class TwoPointsHolder extends Ice.Holder<TwoPoints>
{
    public
    TwoPointsHolder()
    {
    }

    public
    TwoPointsHolder(TwoPoints value)
    {
        super(value);
    }
}
