// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `HelloWorld.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package cn.didadu.generate.helloworld;

public interface Hello extends Ice.Object,
                               _HelloOperations, _HelloOperationsNC
{
    public static final String ice_staticId = "::helloworld::Hello";

    public static final long serialVersionUID = 8058108086137231647L;
}
